spring.application.name=expense-tracker-web

spring.datasource.url=jdbc:mysql://localhost:3306/expense_tracker
spring.datasource.username=root
spring.datasource.password=29suma@V@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080